name: Build FFmpeg RTSP XCFramework

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      ffmpeg_version:
        description: 'FFmpeg Version'
        required: true
        default: '6.1'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install automake fdk-aac git libtool pkg-config shtool yasm nasm wget

      - name: Download gas-preprocessor
        run: |
          # FFmpeg 编译 ARM 架构需要这个脚本处理汇编
          mkdir -p /usr/local/bin
          wget https://github.com/libav/gas-preprocessor/raw/master/gas-preprocessor.pl
          chmod +x gas-preprocessor.pl
          sudo mv gas-preprocessor.pl /usr/local/bin/

      - name: Build FFmpeg
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh ${{ inputs.ffmpeg_version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-xcframework
          path: output/xcframeworks/
